name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pygments
      - run: pip install latexminted
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: template.tex
          latexmk_use_xelatex: true
          args: -shell-escape
          extra_fonts: |
            ./fonts/*.ttf
            ./fonts/*.ttc
            ./fonts/*.TTF
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: template.pdf
